version: "3.2"

services:
  elasticsearch: 
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    volumes: 
    - type: volume
      source: elasticsearch
      target: /usr/share/elasticsearch/data
    environment: 
    - discovery.type=single-node
  mongo:
    image: mongo
    volumes: 
    - type: volume
      source: mongo
      target: /data/db
  graylog: 
    image: graylog/graylog:2.5.1
    environment:   
    - GRAYLOG_WEB_ENDPOINT_URI=http://127.0.0.1:9000/api
    volumes: 
    - type: volume
      source: graylog_journal
      target: /usr/share/graylog/data/journal
    ports: 
    # Graylog web interface and REST API
    - 9000:9000
    # Syslog TCP
    - 514:514
    # Syslog UDP
    - 514:514/udp
    # GELF TCP
    - 12201:12201
    # GELF UDP
    - 12201:12201/udp
    depends_on:
    - elasticsearch
    - mongo
volumes: 
  elasticsearch:
    external: true
  mongo:
    external: true
  graylog_journal:
    external: true